// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLgPedQ_iA1Jc75dqY-L_nL7nDxWyHnEI',
    appId: '1:977904371626:web:6247c81ceb0be279158dd3',
    messagingSenderId: '977904371626',
    projectId: 'ecofinds-a7a42',
    authDomain: 'ecofinds-a7a42.firebaseapp.com',
    storageBucket: 'ecofinds-a7a42.firebasestorage.app',
    measurementId: 'G-BWQ0NQ2QK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAreYer4T3an88q5tlGtuXIfJj5ns7kh4w',
    appId: '1:977904371626:android:2a27653836bf0b63158dd3',
    messagingSenderId: '977904371626',
    projectId: 'ecofinds-a7a42',
    storageBucket: 'ecofinds-a7a42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiihC055HwvHSqGz7ExtEvKMrOl_hZWzE',
    appId: '1:977904371626:ios:9c9f892d1cda41a6158dd3',
    messagingSenderId: '977904371626',
    projectId: 'ecofinds-a7a42',
    storageBucket: 'ecofinds-a7a42.firebasestorage.app',
    iosBundleId: 'com.example.ecoFindsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiihC055HwvHSqGz7ExtEvKMrOl_hZWzE',
    appId: '1:977904371626:ios:9c9f892d1cda41a6158dd3',
    messagingSenderId: '977904371626',
    projectId: 'ecofinds-a7a42',
    storageBucket: 'ecofinds-a7a42.firebasestorage.app',
    iosBundleId: 'com.example.ecoFindsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLgPedQ_iA1Jc75dqY-L_nL7nDxWyHnEI',
    appId: '1:977904371626:web:6c956e9b8416004c158dd3',
    messagingSenderId: '977904371626',
    projectId: 'ecofinds-a7a42',
    authDomain: 'ecofinds-a7a42.firebaseapp.com',
    storageBucket: 'ecofinds-a7a42.firebasestorage.app',
    measurementId: 'G-YG63ZG3QC3',
  );
}
